{{- if not .Values.shadow }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: hello-gateway
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "hello.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number:   80
        name:     http
        protocol: HTTP
      hosts:
        - hello.local
        - "*.hello.local"
{{- end }}
