{{- if not .Values.shadow }}
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "hello.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: "ServerSideApply=true"
spec:
  selector:
    app: hello-service
  ports:
    - name:       http
      port:       80
      targetPort: http
  type: ClusterIP
{{- end }}
